services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: marketing-clickhouse
    environment:
      CLICKHOUSE_DB: marketing
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: marketing-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: marketing-backend
    depends_on:
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      CLICKHOUSE_URL: ${CLICKHOUSE_URL:-clickhouse://clickhouse:9000/marketing}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN:-http://localhost:3000}
      LLM_PROVIDER: ${LLM_PROVIDER:-groq}
      LLM_MODEL: ${LLM_MODEL:-qwen/qwen3-32b}
      LLM_API_KEY: ${LLM_API_KEY:-}
      LLM_TEMPERATURE: ${LLM_TEMPERATURE:-0.2}
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS:-3600}
      RATE_LIMIT_PER_MINUTE: ${RATE_LIMIT_PER_MINUTE:-30}
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

volumes:
  clickhouse-data:
